### ISSUE TITLE
How to assign to a group or a role?

### ISSUE THREAD

**Issue by CptJason** [viewflow/viewflow#137]
In our case, sometimes the task is not finished by one person.
So we have to assign to a group or a role.
Any suggestions?

**Comment by kmmbvnr** [comment]
You can specify the required permission. All users with this permission, could take, assign and execute the task

`viewflow.views.AllQueueListView` lists of all unassigned task available to assign to the user

![viewflow flows py at master viewflow viewflow](https://cloud.githubusercontent.com/assets/282529/13633940/3331ee84-e614-11e5-9287-36e39913ca2f.png)

**Comment by codingjoe** [comment]
@CptJason we had the same issue. But this is really a Django problem, not a viewflow one. Django permissions are not very good. Furthermore Django doesn't have a concept of Roles.
We ended up doing exactly what @kmmbvnr suggests. We used permissions and groups do define roles.

You can use the autogenerated permissions and create a group for each swim lane. You than assign the permissions for each task to the corresponding swim lane.

This sadly isn't save if you have a lot of processes in one app, but again that is because of the bad permission implementation in Django.

**Comment by codingjoe** [comment]
To make this a little more handy, you can automatically assign a task to someone, while executing it. We did that, but it requires a bit more hacking in the View nodes.
If you're interested in that, I can prepare an example.

**Comment by CptJason** [comment]
@codingjoe Yes, I do. I'd appreciate if you can show me the example.

**Comment by kmmbvnr** [comment]
Guys, please don't use issue tracker as QA website.
