### ISSUE TITLE
Django cms support

### ISSUE THREAD

**Issue by Tatoo988** [viewflow/viewflow#159]
Hi guys, does this support django-cms? or django-filer?

**Comment by kmmbvnr** [comment]
Viewflow is the generic workflow library for Django. You can intwgrate it with any project.

**Comment by willseward** [comment]
@Tatoo988 I use this with django-cms in a project, and everything works fine except the hard dependency on the ui provided by viewflow...

**Comment by kmmbvnr** [comment]
Viewflow have no ui dependency. Viewflow.frontend is the separate project available on the PRO,  non AGPL version only.

**Comment by willseward** [comment]
Right, but there are elements of viewflow that cause issues when the provided UI is not utilized like https://github.com/viewflow/viewflow/blob/master/viewflow/flow/views/utils.py#L37. If the urls aren't included, any request that falls back to `get_success_url` will fail because viewflow trys to reverse `{}:detail` before inside the `MessageUserMixin` at https://github.com/viewflow/viewflow/blob/master/viewflow/flow/views/mixins.py#L55
