### ISSUE TITLE
[PRO] Multiple flows within the same app causes url not unique via @rest.register

### ISSUE THREAD

**Issue by variable** [viewflow/viewflow#253]
Say I have an app called 'MRT`, inside the app I have 2 flow definitions.

`Flow_A` and `Flow_B`

both registered via `@rest.register` as below:

```python
@frontend.register
@rest.register
class Flow_A(Flow):
    ....

@frontend.register
@rest.register
class Flow_B(Flow):
    ....
```

When I `runserver`, it raises warning: `?: (urls.W005) URL namespace 'viewflow_rest:mrt' isn't unique. You may not be able to reverse all URLs in this namespace`

The consequences of this is that causing tasks of one of the flow(depends on which one registered last) cannot be url reversed. eg. `Reverse for 'check_size__detail' not found. 'check_size__detail' is not a valid view function or pattern name.`

originally posted on [Stackoverflow](https://stackoverflow.com/questions/58757046/django-viewflow-multiple-flows-within-the-same-app-causes-url-not-unique-via-r)

**Comment by kmmbvnr** [comment]
Yep, viewflow 1.x rest fronted for compatibility reasons uses old url naming theme that cause this.

This could be solved by custom frontend. I've included that sample code  to django-viewflow-pro==1.5.11

You could update and user `'viewflow.rest.apps.ViewflowRestNSConfig' instead of `'viewflow.rest` in the INSTALLED_APPS settings.

Please note, that it would change urls from `/workflow/api/flow_label/task_name/` to `/workflow/api/app_name/flow_label/task_name/` same as for standard frontend.
