### ISSUE TITLE
frontend in the admin ?

### ISSUE THREAD

**Issue by olivierdalang** [viewflow/viewflow#336]
Hi ! Gave viewflow a test run, it looks really nice.

Is there a documented way or a plan to make it possible to have the flow views in Django admin rather than in the material frontend ?

To me there would be many benefits :
- benefit from native django admin features (such as autocomplete foreign keys...) and from existing packages
- reusing an environment we already know (both for users and devs) - IMO a must especially for adopting viewflow in already existing apps that make use of django admin
- less opinionated design (material looks great still in 2021, but will look dated)

If not, do you see any major blocker in implementing it ? (I'd see something like a processmodeladmin subclass, that filters fields according to the current step). Would it make sense to include that

**Comment by kmmbvnr** [comment]
The official statement from the [django docs](https://docs.djangoproject.com/en/3.2/ref/contrib/admin/):

_The admin’s recommended use is limited to an organization’s internal management tool. It’s not intended for building your entire front end around._

Admin internals a creepy complicated, have limited way to extend and suffers from many desgin problems for years, Material Frontend provides compositional approach to build interfaces uses standard class-based-views, instead of all in one class as django admin does.

Actual, Material Frontend [has autocomplete widget](http://docs.viewflow.io/forms_widgets.html). For the look-and-feel I'm working on Viewflow 2.0 with google-material-components - https://docs.djangoproject.com/en/3.2/ref/contrib/admin/

**Comment by olivierdalang** [comment]
Thanks for the reply ! Yes I know that statement, but viewflow makes perfect sense as an organization’s internal management tool too, doesn't it ? (at least I look at it for exactly that usage).

You're unfortunately right about many parts of admin being super complex (aka impossible) to properly override/extend. But it's also very full featured (filters, sorting, hierarchical dates, actions, automatic index pages, now including searchable sidebar, various relation widgets, including quick links to create/edit related objects, search, etc.), and the burden of dealing with that complexity is shared between many devs. It is really effective in building robust management tools in no time.

Anyway, no worries, if at some point I find the time to experiment a bit with a admin implementation of an UpdateProcessView and end up with something working, I'll let you know (and think it could perfectly well live in a separate app)
