### ISSUE TITLE
django-fsm to viewflow.fsm transition guide required

### ISSUE THREAD

**Issue by anandrajB** [viewflow/viewflow#341]
hi , am unable to make a transition from new to approved 
you have mentioned this cookbook repo for refernce right , but i'm facing multiple error's

https://github.com/viewflow/cookbook/tree/v2/fsm101

**localhost/api/review/1/transition/approve**  is not doing anything
the stage from **1 -> 2** , is not changing when hitting above url with **flow.approve()**

can i use field in models like fsmfield in django-fsm package
please share a nice working example for fsm part 
Thank you

**Comment by darahsten** [comment]
Why dont you share exactly you are doing and the errors you are facing @anandrajB

**Comment by anandrajB** [comment]
Hi @darahsten 
i have been using django-fsm in my current project 
i have defined states and transitions like this 

**using django-fsm**

models.py

class workflowitems(models.Model):

    STATE_TYPE = [
        (STATUS_DRAFT, 'DRAFT'),
        (STATUS_ACCEPTED, 'ACCEPTED'),
        (STATUS_APPROVED, 'APPROVED'),
        (STATUS_REJECTED, 'REJECTED'),
    ]
    
    initial_state = **FSMField**(choices = STATE_TYPE , default = STATUS_DRAFT)
 
    @transition(field=initial_state, source=['*'], target=STATUS_REJECTED)
    def reject(self):
        pass
        
  **views.py**
  
@api_view(['GET', 'POST'])
def deleted(self, pk):
    obj = generics.get_object_or_404(workflowitems, id=pk)
    obj.reject()
    obj.save()
    return "data ok " 
       
       
  when using viewflow.fsm how to define field in models 
  
  **using viewflow.fsm**
  
  state = fsm.State(ReportState, default=ReportState.NEW)
  
   @stage.transition(source=ReportState.NEW, target=ReportState.APPROVED)
   def cancel(self):
        self.name = 'UPDATED

 when i hit this cancel funtion , there is no transition is changing from 
 NEW -> APPORVED

**Comment by darahsten** [comment]
Hey, I think you are looking for answers too fast.

I don't see, any ReportState model in your submission. And are you sure. of

    @stage.transition(source=ReportState.NEW, target=ReportState.APPROVED)
    def cancel(self):
        self.name = 'UPDATED'`

I cant see what class (object) the self here refers to.
Therefore I am not sure you are doing the right thing. But since I don't know what you are referring to exactly (that is class). 
I don't think I can give a meaningful comment.
 The transition decorator is used as 

    @transition(field=state, source=ReportState.NEW', target=ReportState.APPROVED)
    def cancel(self):
        """
        This function may contain side-effects,
        like updating caches, notifying users, etc.
        The return value will be discarded.
        """

Please read the brief manual [here.](https://github.com/viewflow/django-fsm#readme)

You have to note, that the transition methods do not make the state persist in the database until the save method
on the object is called

"""If calling publish() succeeds without raising an exception, the state field will be changed, but not written to the database.""".
See the readme.

**Comment by kmmbvnr** [comment]
Please ensure, that you have latest django-viewflow==2.0.0a2 installed

If you are mrating from django-fsm, note that the viewflow.fsm are no longer belongs to the model class

To connect fsm to the django models the following instuction could be used: https://docs-next.viewflow.io/fsm/models.html

Here is also the video describes viewflow.fsm in action - https://www.youtube.com/watch?v=FN_1ykC0LEs

**Comment by anandrajB** [comment]
Thank you

**Comment by anandrajB** [comment]
k
