### ISSUE TITLE
Django 4.1 (upcoming 4.2) support?

### ISSUE THREAD

**Issue by jturmel** [viewflow/viewflow#377]
What's the timeline for Django 4.1 and 4.2 support?

We purchased this for a client site years ago that they moved away from but now they're wanting to revive it which will mean us updating it and buying the latest license, but we'd want to build on the latest Django version if we do.

**Comment by kmmbvnr** [comment]
Thank you for your interest in Viewflow! Both Viewflow 1.x and 2.x are compatible with Django 4.1 and 4.2. However, we recommend using Viewflow 2.x for new projects since it has better support and is more actively maintained.

Please note that Viewflow 1.x open source versions will not receive any updates except for security fixes, while Viewflow 1.x pro versions will only receive bug fixes on customer request.

**Comment by jturmel** [comment]
Great! When will 2.x be out of beta?

**Comment by jturmel** [comment]
Is there any docs on upgrading from 1.x to 2.x?

**Comment by jturmel** [comment]
We used a lot of the formsets/inlines/layout pieces so that's what we're most concerned with in terms of upgrading the existing code that is 1.x to 2.x if we do purchase 2.x, the thing is it's a non-profit client so their budget is pretty small, but we want to get them in the best spot possible since they probably wont' touch it for another few years once we stand their project back up (it's been dormant for about 4 years now).

**Comment by kmmbvnr** [comment]
@jturmel formset and inlines api stays mostly same - https://docs-next.viewflow.io/forms/formsets.html
