### ISSUE TITLE
Please cut a new release for 2.1.1

### ISSUE THREAD

**Issue by jsenecal** [viewflow/viewflow#448]
Pypi now has `django-viewflow-2.1.1` but no changelog is available in the release page of the project.

Please prepare and publish a new release on github to properly identify changes.

Publishing new pypi releases without equivalent releases in github is widely regarded as a security risk as the unreviewed code pulled from pypi may have malicious code added to it should the maintainer's account been compromised.

Thanks !

**Comment by kmmbvnr** [comment]
Thanks for your comment

2.1.1 published soon after 2.1.0 just as hotfix

**Comment by jturmel** [comment]
Bumping this, now on 2.1.2 in pypi but no corresponding releases on the Github side.

**Comment by kmmbvnr** [comment]
Mm, none of my projects since 2010, including Viewflow and its predecessor, django-fsm, have used GitHub releases extensively. I'm actually a bit surprised that this could be an issue for someone.

Viewflow itself is developed in a private Git repository, and only part of the changes are occasionally released as open source without preserving the public Git commit history. For every user who has a project in production and is mindful of security risks, I suggest switching to the PRO version, which is distributed from my private PyPI server. This ensures stable and predictable project involvement while mitigating the security risks associated with the public PyPI repository.

**Comment by jturmel** [comment]
We're not really worried about the security implications, but more on having a release with at least some semblance of a changelog since the source is private.

**Comment by kmmbvnr** [comment]
Changelog is available as in the last part of readme as in the standard location https://github.com/viewflow/viewflow/blob/main/CHANGELOG.rst
