### ISSUE TITLE
BPMN Editor

### ISSUE THREAD

**Issue by rcorzogutierrez** [viewflow/viewflow#90]
Did they could consider include a BPMN editor like http://demo.bpmn.io/?

**Comment by kmmbvnr** [comment]
Probably, there is no reason to bound end users with only one integrated bpmn editor for viewflow.

Even if you create a bpmn structure with graphical editor, than you have to modify code - django models, forms, views and then run tests to get working process.

Adding full-featured workflow constructor will limits you with predefined workflow task and nodes. The main advantage of viewflow is the ability to create custom nodes and forms fields with few amount of code. 

I was quite unhappy with existing bpmn tools for a while.

Viewflow usage assumes that management staff are able to create bpmn diagrams using any bpmn drawing software (and actually visio works so very well. It's fast, reliable and more user friendly than any other web based tool)

On the next step bpmn diagram manually converted to the viewflow.Flow class.

There is a plan to provide ability to autogenerate python code from bpmn file, and/or use bpmn file only for task weaning (instead of .Next() specification in python code).

But it is the last priority. Typical viewflow project contains several thousand lines of backend code (3d party services integration, database models and forms, and tests) and only few thousand lines of flow definition.

So, creating Flow class in real project takes really small amount of time.
