### ISSUE TITLE
No transition from ASSIGNED

### ISSUE THREAD

**Issue by codingjoe** [viewflow/viewflow#97]
Happens in line:
https://github.com/viewflow/viewflow/blob/master/viewflow/activation.py#L758

The problem is in the Task FSM. You can't go from `ASSIGNED` into `CANCELED`. This should be changed, as even the `CancelView` does not handle this properly.

Reproduce:
Split -> task *2 -> Join(wait_all=False)
Assign one task, than complete the other and you'll get the error.

**Comment by kmmbvnr** [comment]
This is the expected behavior. Not all task states are cancelable. Ex: started celery task is not cancelable and can't be canceled anyway.

Here is the check in cancel view:

https://github.com/viewflow/viewflow/blob/master/viewflow/views/actions.py#L116

And there is how the process view handles list of uncancelable tasks:

https://github.com/viewflow/viewflow/blob/master/viewflow/views/actions.py#L68

There is the open question -  should be assigned task be cancelable or not. If should, this could raise bad behavior when end user starts filling the form but they became not able to submit it, without any notification. That's why ASSIGNED->UNASSIGNED transition requires explicit separated action, and decision (may be phone call) from action performer.

Btw, activation transitions could be easily redefined in subclasses or views. I spend months to find good solution on this. So you can create a custom activation class, or redefine it in the View if View implements activation interface.

You can even have your own set of flow.Task classes, that have preconfigured behavior expected by you.

But for me it's hard to decide what behavior should be implemented by default in core library.

**Comment by codingjoe** [comment]
@kmmbvnr agreed, this is a tough call. But bare in mind, the use case I described. If you automatically cancel a task because of `Join(wait_all=False)` I expect it to just work. No matter if it is assigned or not.
You may also add another explicit kwarg like `cancel_others` if that makes it more clear.
I didn't even know, that other tasks are canceled. Tho it is what you want in 90% of all cases.
If you handle the cancellation, it just should handle it, no matter what.

Just to be sure, I didn't say the fsm is wrong. `wait_all=False` should just handle unassigning.

**Comment by kmmbvnr** [comment]
`Join(wait_all=False)` didn't cancels any tasks actually.
